"""phase5_verification_models

Revision ID: ddec9d96e576
Revises: 7eca69296ed6
Create Date: 2026-08-13 15:54:29.874830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddec9d96e576'
down_revision: Union[str, Sequence[str], None] = '7eca69296ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_verifications_id'), 'result_verifications', ['id'], unique=False)
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('correction_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_results_verified_by_users', 'users', ['verified_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_results_verified_by_users', type_='foreignkey')
        batch_op.drop_column('correction_reason')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')
    op.drop_index(op.f('ix_result_verifications_id'), table_name='result_verifications')
    op.drop_table('result_verifications')
    # ### end Alembic commands ###

