"""patient_test_extensions

Revision ID: ef7acd808f6c
Revises: b132f7d7961c
Create Date: 2026-08-12 23:43:41.570413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7acd808f6c'
down_revision: Union[str, Sequence[str], None] = 'b132f7d7961c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('referring_provider', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('consent_operational', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('consent_promotional', sa.Boolean(), nullable=False))
    op.drop_column('patients', 'consent_status')
    op.add_column('test_parameters', sa.Column('critical_low', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('test_parameters', sa.Column('critical_high', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('test_parameters', sa.Column('ref_gender', sa.String(), nullable=True))
    op.add_column('test_parameters', sa.Column('ref_age_min', sa.Integer(), nullable=True))
    op.add_column('test_parameters', sa.Column('ref_age_max', sa.Integer(), nullable=True))
    op.add_column('test_parameters', sa.Column('ref_context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_parameters', 'ref_context')
    op.drop_column('test_parameters', 'ref_age_max')
    op.drop_column('test_parameters', 'ref_age_min')
    op.drop_column('test_parameters', 'ref_gender')
    op.drop_column('test_parameters', 'critical_high')
    op.drop_column('test_parameters', 'critical_low')
    op.add_column('patients', sa.Column('consent_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('patients', 'consent_promotional')
    op.drop_column('patients', 'consent_operational')
    op.drop_column('patients', 'referring_provider')
    # ### end Alembic commands ###
